### ISSUE TITLE
Suggestion: Make commands callable from python code

### ISSUE THREAD

**Issue by yeahnope** [ledesmablt/spotify-cli#14]
I am aware that this is not the primary goal of this project, but it would be nice if one could also call all methods from within pyhon code. As far as I can tell this currently only works as expected for methods without arguments, e.g. the following works:
```python
import cli.spotify
cli.spotify.play()
cli.spotify.pause()
cli.spotify.previous()
cli.spotify._next()
```
But this does not:
```python
cli.spotify.volume("up", 10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 712, in main
    _bashcomplete(self, prog_name, complete_var)
  File "/usr/lib/python3/dist-packages/click/core.py", line 51, in _bashcomplete
    complete_var = '_%s_COMPLETE' % (prog_name.replace('-', '_')).upper()
AttributeError: 'int' object has no attribute 'replace'
```
neither does this:
```python
cli.spotify.volume("up", "10")
Usage: 10 [<options>] <mode> <amount>
Try "10 --help" for help.

Error: Invalid value for "<mode>": invalid choice: u. (choose from to, up, down)
```
neither does this:
```python
cli.spotify.volume("up 10")
Usage: core.py [<options>] <mode> <amount>
Try "core.py --help" for help.

Error: Invalid value for "<mode>": invalid choice: u. (choose from to, up, down)
```

So it would be nice if the click commands could be wrappers around the actual methods. I haven't tested it but something like this should work:
```python
def volume(mode, amount):
    # The actual definition of the method stays here 
    # (its just omitted to aid readability of this suggestion)

@click.command(options_metavar='[<options>]', name='volume') # Name must be specified explicitly
@click.argument(
    'mode', type=click.Choice(['to', 'up', 'down'], case_sensitive=False),
    metavar='<mode>'
)
@click.argument(
    'amount', type=int,
    metavar='<amount>'
)
def volume_command(mode, amount):
    volume(mode, amount)
```

If wanted, I can make a PR to change this for all commands

**Comment by ledesmablt** [comment]
Hey @yeahnope you can actually call the "unwrapped" callback function. See image below for an example.

Regarding making the click commands wrappers around the actual methods -- since the package is intended to be used only as a CLI, I'd like to keep the "wrapped" functions as the default design pattern. I'd refrain from giving the impression that the package also works as a function library, since that would imply having thorough docs and handling more edge cases.

If you haven't checked out [Spotipy](https://spotipy.readthedocs.io/en/2.18.0/) yet, it might be closer to what you're looking for.

![image](https://user-images.githubusercontent.com/22242264/119472194-9c408300-bd7c-11eb-8dc8-2489a918c08b.png)

**Comment by yeahnope** [comment]
Thanks! Calling 
`cli.spotify.volume.callback("up", 10)`
instead of
`cli.spotify.volume("up", 10)`
did the trick. 
The only reason why I opened this issue was to avoid `subprocess.Popen(["spotify", "volume", "up", "10"])` :wink:
