### ISSUE TITLE
bin filename conflicts with offical binary name

### ISSUE THREAD

**Issue by skamansam** [ledesmablt/spotify-cli#16]
After installing the cli library, I am having issues runnig the spotify desktop player. As you can see, there are two `spotify`s in my path:

```
> whereis spotify
spotify: /home/sam/.pyenv/shims/spotify /var/lib/snapd/snap/bin/spotify
```
To resolve this issue, I ran the following command, but I think there should not be a confict to begin with:
```
> mv `which spotify` `which spotify`-cli
> whereis spotify
spotify: /var/lib/snapd/snap/bin/spotify
> whereis spotify-cli
spotify-cli: /home/sam/.pyenv/shims/spotify-cli
```

**Comment by ledesmablt** [comment]
Hi @skamansam thanks for raising this, it was actually a concern of mine before. Though I eventually came to the conclusion that these kinds of conflicts are unavoidable, especially when it comes to CLI tools that concern mainstream services like Spotify.

There are several ways to work around this (like how you did it) which is why I didn't bother too much to give it a unique name. For what it's worth, the convenience of having it as just `spotify` seems to be working out for the many people who use it regularly.

Another workaround I'd suggest for these kinds of conflicts would be something like this:

```bash
# in your .bashrc or .zshrc

alias spotify=/var/lib/snapd/snap/bin/spotify
alias spotify-cli=/home/sam/.pyenv/shims/spotify  # instead of renaming the executable itself
```

Personally my spotify-cli command is aliased to `sp` so that it's quick to type.

**Comment by skamansam** [comment]
Thank you! Since this has been officially addressed, I will close it.

**Comment by hugeblank** [comment]
A bit more clear guide for adding the two lines to your `.*rc` files, for those unfamiliar with commands:
1. Find the two files using `whereis spotify`. This should give you two results, in my case, `spotify: /usr/bin/spotify /home/hugeblank/.local/bin/spotify`.
2. Determine which is which. In my case when running `/usr/bin/spotify` it runs the generic client, `/home/hugeblank/.local/bin/spotify` was spotify-cli.
3. add the two aliases using the method @ledesmablt provides.
