### ISSUE TITLE
Operation restricted for the active device error on volume change in bash

### ISSUE THREAD

**Issue by illiakozey** [ledesmablt/spotify-cli#18]
When trying to change volume by the `$ spotify-cli v up/down/to 50` command, an error `Error: Operation restricted for the active device.` appears

**Comment by ledesmablt** [comment]
Hi @illiakozey , the volume command in particular is expected to not work for mobile (noted in readme [here](https://github.com/ledesmablt/spotify-cli#notes)). I'm not sure why the Spotify API doesn't work here, but my guess is that Spotify mobile depends only on device volume (no in-app volume), as opposed to the web and desktop client which both depend on your system volume and the Spotify app's volume levels.

I'd say this isn't a bug on the cli or the API since we can't expect Spotify to be able to hijack your system volume =)

**Comment by illiakozey** [comment]
hmm, but an error appears when im trying to change volume using bash on desktop Spotify client

**Comment by ledesmablt** [comment]
Can you run `spotify status -vv` and confirm that your device is indeed the desktop client?

If so, are you using Spotify premium? [Docs](https://developer.spotify.com/documentation/web-api/reference/#endpoint-set-volume-for-users-playback) state that non premium users will get an error message, though I haven't tested this before

**Comment by illiakozey** [comment]
yes, an output says `Device  dhcpph4 (Computer)` + im not using Spotify premium

**Comment by ledesmablt** [comment]
Okay, so that means the error is due to you not using Spotify premium. Can't really help with this since this is a limitation they set in their API. Thanks for raising this though!
